name: Build Docker and Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create mongoDB Docker container
      run: |
        sudo docker build -t test_mongo_tgfp -f Dockerfile-Tst .
        sudo docker run -d \
        -p ${{ secrets.MONGO_PORT }}:27017 \
        test_mongo_tgfp
