name: Build Docker and Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONPATH: ./tgfp_lib
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev_requirements.txt
    - name: Run pytest
      run: |
        pytest tests

